# Use root/example as user/password credentials
version: '3.1'

services:

  storefront-db:
    container_name: storefront-db
    image: mysql:8.0.30
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: example

  storefront-adminer:
    container_name: storefront-adminer
    image: adminer
    restart: always
    depends_on:
      - storefront-db
    ports:
      - 8080:8080

networks:
  storefront: